import statsVenture from "@/assets/stats-venture.png";
import statsVenture2 from "@/assets/stats-venture-2.png";

export default function WhyVenture() {
  return (
    <section className="bg-[#f5f3f0] py-30">
      <div className="max-w-4xl mx-auto text-center px-6 space-y-6 mb-20">
        <p className="uppercase tracking-wide text-sm text-gray-500 font-medium">
          Why Venture
        </p>
        <h2 className="text-4xl md:text-5xl font-atlantix text-gray-900">
          Same problem, different asset
        </h2>
        <p className="text-gray-700 text-lg leading-relaxed">
          Like real estate, the world of investing in private technology companies has remained almost entirely inaccessible to individuals, despite the fact that as an asset class it has proven to be one of (if not the) best performing investment strategies of the past 50 years.
        </p>
      </div>

      <div className="max-w-6xl flex flex-col md:flex-row  mx-auto px-6 gap-16 items-start">
        {/* Left Column: Text */}
        <div className="space-y-6 w-1/3 sticky top-32">
          <h3 className="text-2xl md:text-4xl font-sectra text-gray-900">
            Vast majority of returns accrue in the private markets
          </h3>
          <p className="text-gray-700 text-base leading-relaxed">
            With companies staying private longer, the vast majority of the returns from private tech has accrued to the private investors before the public offering. Plus, access is gated, with hefty tolls, by fund managers and growth equity firms, just as in the real estate private equity world.
          </p>
          <p className="text-gray-700 text-base leading-relaxed">
            During the 90's and early 00's, companies like Amazon and Google went public relatively soon in their growth cycle, while companies today are waiting on average 10 years longer. The result: individual investors confined to the public markets are missing out on a substantial portion of the returns generated by the next generation of industry leaders.
          </p>
        </div>

        {/* Right Column: Sticky Chart Image */}
        <div className=" w-2/3">
          <img
            src={statsVenture}
            alt="Venture stats chart"
            className="rounded-sm w-full h-auto object-cover"
          />
          <p className="text-gray-700 mt-6 italic text-[11px] text-base leading-relaxed">
            Source: Robert S. Harris, Tim Jenkinson, and Steven N. Kaplan, “How Do Private Equity Investments Perform Compared to Public Equity?” Journal of Investment Management, Vol. 14, No. 3, Third Quarter 2016, 1-24; Steve Kaplan, “What Do We Know About Private Equity Performance?” Guest Lecture at Miami Herbert Business School, January 31, 2020; Steve Kaplan, “What Do Venture Capitalists Do? How Well Have They Done?” University of Chicago Booth School of Business; FactSet; NAREIT; Refinitiv; and Aswath Damodaran.
          </p>
          <p className="text-gray-700 mt-4 mb-8 italic text-[11px] text-base leading-relaxed">
            Note: Past performance is no guarantee of future returns; All asset classes reflect 1984-2015 except for VC, which reflects 1984-2013; Return for Buyout and VC is measured by weighted average internal rate of return (IRR); All asset classes are for the U.S. except for Non-U.S. Equities and Commodities (Buyout and VC have a North American focus).
          </p>

          <img
            src={statsVenture2}
            alt="Venture IPO chart"
            className="rounded-sm w-full h-auto object-cover"
          />
        </div>
      </div>
    </section>
  );
}
